/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AulasRouteImport } from './routes/aulas'
import { Route as ProfesoresRouteImport } from './routes/profesores'
import { Route as TarjetasRouteImport } from './routes/tarjetas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasRoute = AulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesoresRoute = ProfesoresRouteImport.update({
  id: '/profesores',
  path: '/profesores',
  getParentRoute: () => rootRouteImport,
} as any)
const TarjetasRoute = TarjetasRouteImport.update({
  id: '/tarjetas',
  path: '/tarjetas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/profesores': typeof ProfesoresRoute
  '/tarjetas': typeof TarjetasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/profesores': typeof ProfesoresRoute
  '/tarjetas': typeof TarjetasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/profesores': typeof ProfesoresRoute
  '/tarjetas': typeof TarjetasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aulas' | '/profesores' | '/tarjetas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aulas' | '/profesores' | '/tarjetas'
  id: '__root__' | '/' | '/aulas' | '/profesores' | '/tarjetas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AulasRoute: typeof AulasRoute
  ProfesoresRoute: typeof ProfesoresRoute
  TarjetasRoute: typeof TarjetasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas': {
      id: '/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesores': {
      id: '/profesores'
      path: '/profesores'
      fullPath: '/profesores'
      preLoaderRoute: typeof ProfesoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarjetas': {
      id: '/tarjetas'
      path: '/tarjetas'
      fullPath: '/tarjetas'
      preLoaderRoute: typeof TarjetasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AulasRoute: AulasRoute,
  ProfesoresRoute: ProfesoresRoute,
  TarjetasRoute: TarjetasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
